### ISSUE TITLE
Temporal Type

### ISSUE THREAD

**Issue by rmscheller** [LANDIS-II-Foundation/Extension-Base-BDA#5]
Reported by AMGdeBruijn, Apr 16, 2014
What steps will reproduce the problem?

Set in the input file
TemporalType continuous << pulse, variablepulse,or continuous
What is the expected output?
model should run

What do you see instead? error message: invalid selection, should be pulse, variablepulse or continuous

**Comment by bmarron18** [comment]
QAQC_Example, base-BDA-Input_s1e1.txt from scenario_s1e1_QAQC.txt used to test by setting
TemporalType continuous 	<< pulse, variablepulse,or continuous

No exception thrown; close issue

[PWL83_QAQC_BaseBDA_20171005 .txt](https://github.com/LANDIS-II-Foundation/Extension-Base-BDA/files/1359420/PWL83_QAQC_BaseBDA_20171005.txt)
